replicaCount: 1

image:
  repository: ghcr.io/jcbodero/telcox-catalog-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

basePath: /catalog-service

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: traefik
  host: catalog.telcox.local
  annotations: {}

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

