apiVersion: v1
kind: Service
metadata:
  name: {{ include "telcox-keycloak.postgresqlName" . }}
  labels:
    {{- include "telcox-keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    {{- include "telcox-keycloak.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
