apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "telcox-keycloak.postgresqlName" . }}
  labels:
    {{- include "telcox-keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgresql.storage.storageClassName }}
  storageClassName: {{ .Values.postgresql.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
