replicaCount: 1

image:
  repository: ghcr.io/jcbodero/telcox-customer-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

basePath: /customer-service

audit:
  backend: memory
  postgresUrlSecretName: telcox-postgres-auth
  postgresUrlSecretKey: url

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: traefik
  host: reto1.telcox.site
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi



