replicaCount: 1

image:
  repository: ghcr.io/jcbodero/telcox-sri-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

basePath: /sri-service

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: traefik
  host: reto1.telcox.site
  tls:
    enabled: true
    secretName: telcox-sri-service-tls
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

resources:
  requests:
    cpu: 20m
    memory: 96Mi
  limits:
    cpu: 80m
    memory: 160Mi
