apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  labels:
    app.kubernetes.io/name: grafana
    {{- include "telcox-observability.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}

