replicaCount: 1

image:
  repository: mongo
  tag: "7.0"
  pullPolicy: IfNotPresent

auth:
  database: telcox_audit
  username: admin
  existingSecret: ""
  usernameKey: username
  passwordKey: password
  password: ""

service:
  type: ClusterIP
  port: 27017

storage:
  size: 8Gi
  storageClassName: ""

resources:
  requests:
    cpu: 50m
    memory: 192Mi
  limits:
    cpu: 150m
    memory: 384Mi

initdb:
  enabled: true
