replicaCount: 1

image:
  repository: ghcr.io/jcbodero/telcox-billing-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

basePath: /billing-service

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: traefik
  host: TU_SUBDOMINIO.duckdns.org
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: duckdns

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi


