apiVersion: v1
kind: Service
metadata:
  name: kyc-identity-mock
  namespace: {{ .Values.namespace.name | quote }}
spec:
  type: {{ .Values.kyc.service.type }}
  selector:
    app.kubernetes.io/name: kyc-identity-mock
  ports:
    - port: {{ .Values.kyc.service.port }}
      targetPort: {{ .Values.kyc.service.targetPort }}
