apiVersion: v1
kind: Service
metadata:
  name: network-oss-mock
  namespace: {{ .Values.namespace.name | quote }}
spec:
  type: {{ .Values.networkOss.service.type }}
  selector:
    app.kubernetes.io/name: network-oss-mock
  ports:
    - port: {{ .Values.networkOss.service.port }}
      targetPort: {{ .Values.networkOss.service.targetPort }}
