apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-mock
  namespace: {{ .Values.namespace.name | quote }}
spec:
  type: {{ .Values.paymentGateway.service.type }}
  selector:
    app.kubernetes.io/name: payment-gateway-mock
  ports:
    - port: {{ .Values.paymentGateway.service.port }}
      targetPort: {{ .Values.paymentGateway.service.targetPort }}
