replicaCount: 1

image:
  repository: ghcr.io/jcbodero/telcox-onboarding-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

basePath: /onboarding-service

identity:
  provider: keycloak
  keycloakRealm: telcox
  kycProvider: mock-kyc
  faceProvider: mock-face-match

audit:
  backend: postgres
  postgresUrlSecretName: telcox-postgres-auth
  postgresUrlSecretKey: url

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: traefik
  host: reto1.telcox.site
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi



