replicaCount: 1

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

auth:
  database: telcox_audit
  username: telcox
  existingSecret: ""
  passwordKey: password
  password: ""

service:
  type: ClusterIP
  port: 5432

storage:
  size: 8Gi
  storageClassName: ""

resources:
  requests:
    cpu: 50m
    memory: 160Mi
  limits:
    cpu: 150m
    memory: 384Mi

initdb:
  enabled: true
