replicaCount: 1

image:
  repository: ghcr.io/jcbodero/telcox-ui
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  host: reto1.telcox.site
  path: /
  tls:
    enabled: true
    secretName: telcox-ui-tls
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "1"
    traefik.ingress.kubernetes.io/router.tls: "true"

manuals:
  enabled: true
  path: /manuales
  auth:
    enabled: true
    existingSecret: telcox-manuals-basic-auth
    middlewareName: telcox-manuals-basic-auth
    realm: TelcoX Manuales
  ingress:
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "100"
      traefik.ingress.kubernetes.io/router.tls: "true"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 192Mi
