apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.duckdns.acme.email=julio.home96@gmail.com"
      - "--certificatesresolvers.duckdns.acme.storage=/data/acme.json"
      - "--certificatesresolvers.duckdns.acme.dnschallenge.provider=duckdns"
      - "--certificatesresolvers.duckdns.acme.dnschallenge.delaybeforecheck=30"
      - "--certificatesresolvers.duckdns.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
    env:
      - name: DUCKDNS_TOKEN
        valueFrom:
          secretKeyRef:
            name: duckdns-token
            key: token
    persistence:
      enabled: true
      path: /data
      size: 128Mi
